# Forward particle tracing through the steady velocity field written by flow.ini.
# Darcy flux 0.02 m/d, porosity 0.3: pore velocity 0.0667 m/d in +x.

[Data]
Prefix = out/box
Particle_file = input/particles.dat

[Simulation]
Delta_time_file = input/trace_dt.dat
Porosity = 0.3

[Output]
Prefix = trace/box

[Misc]
Dbg_prefix = trace/dbg
